### ISSUE TITLE
Can Dataset support accessKey and secretAccessKey in Secret?

### ISSUE THREAD

**Issue by davidyuyuan** [IBM/dataset-lifecycle-framework#30]
Can Dataset support preexisting Secret where accessKeyID and secretAccessKey are stored? There may be two reasons:

1. End users do not want to store such information in Dataset if they open-sourced their project. It can be a security risk.
2. In larger organizations, such information may not be available to programmers. Administrators create K8S Secret on their behalf. 

Related, the rest of the information: endpoint, bucket, region may be available in a configmap. Please consider that as secondary.

**Comment by YiannisGkoufas** [comment]
Thanks @davidyuyuan it definitely makes sense, it's not difficult to implement, will definitely be able to support it soon.

**Comment by srikumar003** [comment]
This is now supported by PR #73 (accepted). Closing this issue to reflect this.
