### ISSUE TITLE
Addressing by name or ID

### ISSUE THREAD

**Issue by vpavlin** [IBM/dataset-lifecycle-framework#32]
The README states addressing of datasets is done by "using the unique ID defined at creation time" - when I look at the example it looks like the addressing is done by the name of dataset CR - can you maybe clarify that in the README?

**Comment by YiannisGkoufas** [comment]
Nice catch @vpavlin
You are right, it's the name that is used. Also a PVC will be created with the exact same name.
Updated the README accordingly
