### ISSUE TITLE
Multiple namespaces installation problems

### ISSUE THREAD

**Issue by YiannisGkoufas** [IBM/dataset-lifecycle-framework#35]
If you do the full installation on a different namespace, the previous installation breaks.
We need to have 2 things fixed

- In the installation to check if the dataset operator is running in another namespace and prevent re-installation
- Explain on the wiki how to extend existing installation to multiple namespaces

FYI @davidyuyuan

**Comment by davidyuyuan** [comment]
In this case, it might be better to make the operator to watch all namespaces by default. We give users an option to watch a list of namespaces if they want to, and document how they can update the list later.
