### ISSUE TITLE
Existing files owned by root inaccessible by nonroot users

### ISSUE THREAD

**Issue by davidyuyuan** [IBM/dataset-lifecycle-framework#36]
Storage buckets work nicely if they are empty. The existing files and directories are owned by root so they are inaccessible by non-root users in a container. I have tried object stores on GCP, AWS and a custom S3-compatible object store. Note that this applies to the files and directories created outside of DLF via S3 APIs. The ones created via DLF have the correct ownership if a bucket is mounted a second time.

**Comment by YiannisGkoufas** [comment]
Thanks @davidyuyuan I just tested the fix on https://github.com/IBM/dataset-lifecycle-framework/commit/8ff2ee33796186193fd2bac48f51c0e3de09c9cc and it looks like it's solved, but please verify in your environment.
With this fix, you can mount under /home/jovyan in your notebooks as well and use it without a problem

**Comment by davidyuyuan** [comment]
Thank you for the prompt response. The issue has been fixed. DLF now works nicely with notebook servers on Kubeflow. I think that we can close the issue now.
