### ISSUE TITLE
Show example of using python apis

### ISSUE THREAD

**Issue by YiannisGkoufas** [IBM/dataset-lifecycle-framework#38]
Document an example of using python's k8s apis, ie `create_namespaced_custom_object`

cc @davidyuyuan

**Comment by davidyuyuan** [comment]
+1

**Comment by YiannisGkoufas** [comment]
@davidyuyuan have a look on the updated guide for creating datasets as part of the pipeline https://github.com/IBM/dataset-lifecycle-framework/wiki/PVCs-for-Pipelines-SDK#example-with-creation-of-dataset-as-part-of-the-pipeline-execution

**Comment by YiannisGkoufas** [comment]
And this is the example pipeline https://github.com/IBM/dataset-lifecycle-framework/blob/master/examples/kubeflow/volumeop.py

**Comment by YiannisGkoufas** [comment]
@davidyuyuan in line with the approach followed here: https://github.com/kubernetes-client/python/issues/740

You can adopt it as follows:

```
import yaml
from kubernetes import client

DLF_API='com.ie.ibm.hpsys'
DLF_API_VERSION='v1alpha1'

aConfiguration = client.Configuration()
aConfiguration.host = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
aConfiguration.api_key = {"authorization": "Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
aConfiguration.verify_ssl = False
clientapi = client.ApiClient(aConfiguration)
customObjectApi = client.CustomObjectsApi(clientapi)

yaml_data= """
{"apiVersion":"com.ie.ibm.hpsys/v1alpha1","kind":"Dataset","metadata":{"name":"your-dataset"},"spec":{"local":{"accessKeyID":"XXXXXXXXXXX","bucket":"mybucket","endpoint":"http://s3.eu.cloud-object-storage.appdomain.cloud","region":"","secretAccessKey":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","type":"COS"}}}
"""

customObjectApi.create_namespaced_custom_object(DLF_API, DLF_API_VERSION, 'default', 'datasets', yaml.load(yaml_data,Loader=yaml.FullLoader))
```
Let me know if it works for you so I can close this one

**Comment by davidyuyuan** [comment]
@YiannisGkoufas , Here is what I did:
def k8s_ds_op(name: str,
              manifest: str,
              action: str = "apply") -> PipelineVolume:
    with open(manifest, 'r') as fp:
        yml = yaml.safe_load(fp)
    print(yml)
    k8s_resource = V1beta1CustomResourceDefinition(api_version=yml['apiVersion'],
                                                   kind=yml['kind'],
                                                   metadata=yml['metadata'],
                                                   spec=yml['spec'])
    rop = ResourceOp(
        name=name,
        k8s_resource=k8s_resource,
        action=action
    )
    return PipelineVolume(pvc=name).after(rop)

I used V1beta1CustomResourceDefinition because kfp supports v1beta at present. Their latest branch supports V1CustomResourceDefinition. The input YAML is just the CRD of DLF. I think that I did not explain the details well enough. Apologies. I am sure that your sample code above would work as well. Please close this issue. You do not need to change the documentation with the new sample code, either.

**Comment by YiannisGkoufas** [comment]
Ahhh that's great @davidyuyuan the sample is still valid in python k8s api outside of the pipelines SDK context.
