### ISSUE TITLE
Errors during `make minikube-install`

### ISSUE THREAD

**Issue by lukemarsden** [IBM/dataset-lifecycle-framework#41]
Running `make minikube-install` mostly seems to work, but between loading the images into minikube and applying the yaml, spits out these errors:

```
/bin/bash: ./release-tools/generate-keys.sh: No such file or directory
/bin/bash: line 1: /tmp/tmp.w89e0ut2NV/ca.crt: No such file or directory
W0921 17:11:40.845263  162519 helpers.go:535] --dry-run is deprecated and can be replaced with --dry-run=client.
error: Cannot read file /tmp/tmp.w89e0ut2NV/webhook-server-tls.crt, open /tmp/tmp.w89e0ut2NV/webhook-server-tls.crt: no such file or directory
error: no objects passed to apply
/bin/bash: line 5: ./src/dataset-operator/deploy/webhook.yaml.template: No such file or directory
error: no objects passed to apply
```

It seems like the `generate-keys.sh` stuff happens in-cluster now, so maybe this is nothing to worry about? It's a bit disconcerting though :-)

**Comment by YiannisGkoufas** [comment]
Apologies @lukemarsden the documentation is all over the place currently! I have been updating the wiki ( https://github.com/IBM/dataset-lifecycle-framework/wiki/Installation ) but not the README.md (promise to fix it the next few days)
Instead if you use `make deployment` it should work without a problem, let me know if that's not the case.

**Comment by YiannisGkoufas** [comment]
Hi @lukemarsden, with the updated instructions and yamls this should be resolved right?
