### ISSUE TITLE
DaemonSets csi-s3 and csi-nodeplugin-nfsplugin are unable to create pods due to missing RBAC configuration for ServiceAccounts

### ISSUE THREAD

**Issue by VassilisVassiliadis** [IBM/dataset-lifecycle-framework#52]
The [manifest file](https://raw.githubusercontent.com/IBM/dataset-lifecycle-framework/master/release-tools/manifests/dlf.yaml) does not configure the SecurityContextConstraints for the following ServiceAccounts:

- `csi-provisioner`
- `csi-s3`
- `csi-nodeplugin`
- `csi-attacher`

As a result, on OpenShift, containers which are expecting to run in privileged mode are unable to get access to features such as hostNetwork, and hostPath. In turn, the DaemonSets `csi-s3 `and `csi-nodeplugin-nfsplugin` are unable to spawn pods on the cluster nodes because the ServiceAccounts `csi-s3` and `csi-nodeplugin` are not registered as users in the `privileged` SecurityContextConstraints. Similar issues manifest due to the ServiceAccounts `csi-attacher` and `csi-provisioner` not being registered as users in the `privileged` SecurityContextConstraints.

**Done when**

The instructions in the README.md file address the RBAC configuration of the service accounts. This can either be done via

```bash
oc adm policy add-scc-to-user privileged -n dlf -z csi-provisioner -z csi-s3 -z csi-nodeplugin -z csi-attacher
```

alternatively, the instructions could use the JSON patch feature of the `kubectl` utility like so:

```bash
kubectl patch scc privileged --type=json -p '[
  {"op": "add", "path": "/users/-", "value": "system:serviceaccount:dlf:csi-provisioner"}, 
  {"op": "add", "path": "/users/-", "value": "system:serviceaccount:dlf:csi-nodeplugin"}, 
  {"op": "add", "path": "/users/-", "value": "system:serviceaccount:dlf:csi-attacher"}, 
  {"op": "add", "path": "/users/-", "value": "system:serviceaccount:dlf:csi-s3"}]'
```

**Comment by YiannisGkoufas** [comment]
I think that the approach followed here https://github.com/IBM/dataset-lifecycle-framework/tree/openshift-fix is better.
Using `make manifests` the developer exports the dlf-oc.yaml as well and an openshift user can do instead `kubectl apply -f https://raw.githubusercontent.com/IBM/dataset-lifecycle-framework/master/release-tools/manifests/dlf-oc.yaml`
What do you think?

**Comment by VassilisVassiliadis** [comment]
I tried spinning up DLF with the new `release-tools/manifests/dlf-oc.yaml` YAML file on our OpenShift 4 cluster just now, and it works like a charm - I can see the StatefulSet and DaemonSet pods transitioning to the running state.

Thank you!
