### ISSUE TITLE
Questions on the csi-nodeplugin rbac

### ISSUE THREAD

**Issue by Tomcli** [IBM/dataset-lifecycle-framework#64]
From https://github.com/IBM/dataset-lifecycle-framework/blob/master/src/csi-driver-nfs/chart/templates/csi-nodeplugin-rbac.yaml#L38

Should this rbac map to the namespace where `csi-nodeplugin` SA is deployed? Looks like this is a typo.

**Comment by YiannisGkoufas** [comment]
Indeed! Thanks for the fix!
