### ISSUE TITLE
Support specifying which cache plugin (or None) to use for a particular dataset

### ISSUE THREAD

**Issue by pkoutsov** [IBM/dataset-lifecycle-framework#68]
I noticed that at the moment DLF will query for the installed caching plugins and will always use the first result (if any) to cache the dataset. However, in the case where multiple caching plugins are installed, it would come handy to be able to specify which one to use and cache the dataset. Also, there are cases that the user may want to opt-out of caching at all. 

As a solution to the above points, I am thinking that a new label in the dataset, with the key ```cache.plugin``` and as value the name of the caching plugin to use, could be used to identify which plugin to use against the installed ones. Also, when the value of this plugin is ```None``` the user could easily opt-out caching the dataset.

Any thoughts?

Thanks

**Comment by YiannisGkoufas** [comment]
Makes sense! I would still keep the approach cache.label in case we want to have a default cache plugin unless it's specified
